server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 119.45.207.29:22122
    -
mingrui:
  upload:
    path:
      windows: D:\Com.MingRui.Zc\zhengchong_projects\images
      linux: /zhengchong/images
    img:
      host: http://119.45.207.29/